### ISSUE TITLE
Add colors attribute for games

### ISSUE THREAD

**Issue by M4gie** [sQuiz-2/Core#12]
**Is your feature request related to a problem? Please describe.**
Game cards in the frontend are display with a linear gradient
![image](https://user-images.githubusercontent.com/33150916/97110153-e0c94a80-16d7-11eb-92a1-581032426a0d.png)
But currently we don't store any color in the database, we should store linear gradient colors to have different cards like that
![image](https://user-images.githubusercontent.com/33150916/97110173-07878100-16d8-11eb-8800-61b018deab12.png)

**Describe the solution you'd like**
In the API, create a database migration to add the column column `colors`
node ace make:migration game --table games
The column `colors` is a string of 80 chars maximum and it should be nullable

**Comment by JulesDT** [comment]
2 Cents: I'm not sure we need to put the color as a column in the database. I guess the number of difficulties will be a constant, so we could just associate with each difficulty a color that the frontend can reuse.

Also if we wanted to go with a color in the database, rather than a `varchar(80)`, I think it'd be better to have a list of acceptable values like an enum to avoid confusion, typos, or unexisting colors.

**Comment by M4gie** [comment]
Yes you're right, we don't plan to add difficulties so I could use a switch in the frontend
